### ISSUE TITLE
When I try to follow README.md instructions I get errors -> should I be using NODE 18?

### ISSUE THREAD

**Issue by zachzeus** [uncefact/project-vckit#143]
**Describe the bug**
I get warnings and errors out with "Cannot find module" when I run  "pnpm vckit config"

**To Reproduce**
1. Do git pull to get current changes on branch "next"
2. Confirm Node 16
3. Run "pnpm install"
4. This gave a lot of warnings suggesting I use NODE 18
5. Run "pnpm vckit config"
6. Got error

**Expected behavior**
I expected to not get errors.  I don't know if it's my configuration, or if I should be using NODE 18

**Screenshots**
<img width="1041" alt="image" src="https://github.com/uncefact/project-vckit/assets/1311010/25481171-4090-4c69-a14f-fc03692e7368">
Warnings when running "pnpm install"

<img width="1268" alt="image" src="https://github.com/uncefact/project-vckit/assets/1311010/37d015f5-419a-466b-8aac-20d192b884f7">
Error when running  "pnpm vckit config"

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser N/A
 - Version Ventural 13.4.1

**Additional context**
Happy to try with Node 18...

**Comment by namhoang1604** [comment]
Hi @zachzeus, your contribution is greatly appreciated!
The node version should be 18 . Thank you, and feel free if you have more questions.

**Comment by zachzeus** [comment]
Ok I've used Node 18 and pnpm 8.6 and I'm still getting the 2nd error when I run "pnpm vckit config" - > module not found vkit.js.

<img width="1137" alt="image" src="https://github.com/uncefact/project-vckit/assets/1311010/fc1e5d8c-4106-4530-9db5-1a341f33e170">

Here are the warnings I got when I ran "pnpm install"
<img width="1142" alt="image" src="https://github.com/uncefact/project-vckit/assets/1311010/93eac0f2-2449-4608-accf-7448628496cd">

**Comment by namhoang1604** [comment]
That is a mistake for arrange of commands. It needs to run the build command first.
```
# Install dependencies
pnpm install

# Copy the .env.example file to .env for the demo explorer
cp packages/demo-explorer/.env.example packages/demo-explorer/.env

# Build
pnpm build

# Initialize the agent configuration
pnpm vckit config
```
Related PR: https://github.com/uncefact/project-vckit/pull/145

Thank you.

**Comment by zachzeus** [comment]
Getting further:  This is the error that I get now.
<img width="1788" alt="image" src="https://github.com/uncefact/project-vckit/assets/1311010/2955db1b-ddb6-4fe6-bdb3-85e6c2e1836b">

**Comment by namhoang1604** [comment]
Hi @zachzeus, can you provide your pnpm version?

**Comment by zachzeus** [comment]
Its 8.6.12... do I need to go back to 8.6.0?

**Comment by namhoang1604** [comment]
Yes. you need to back to 8.6.0.
