### ISSUE TITLE
Error with @veramo/credential-status while following docs

### ISSUE THREAD

**Issue by Givo29** [uncefact/project-vckit#226]
**Describe the bug**
After following the getting started docs which all completed successfully:
```
# Install dependencies
pnpm install

# Copy the .env.example file to .env for the demo explorer
cp packages/demo-explorer/.env.example packages/demo-explorer/.env

# Build
pnpm build

# Initialize the agent configuration
pnpm vckit config
```

When trying to run any pnpm vckit script like `pnpm vckit server`, `pnpm vckit execute`, `pnpm seed-identifier`, I get the following error:
![image](https://github.com/user-attachments/assets/bba5db0d-d7ee-463d-a7ca-c2110a111b1c)

**To Reproduce**
1. Follow getting started commands
2. Attempt to start vckit

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome 126.0.x

**Comment by ashleythedeveloper** [comment]
Hi @Givo29, thanks for reaching out.

I will take a look at this today and get back to you.

**Comment by ashleythedeveloper** [comment]
Hi @Givo29,

I've pulled down a fresh clone of the repo (next branch) and followed the getting started steps:

**Versions**
node: v20.12.2
pnpm : 8.14.1
yarn: 1.22.22

**Commands**
pnpm install
cp packages/demo-explorer/.env.example packages/demo-explorer/.env
pnpm build
pnpm vckit config
pnpm seed-identifier
pnpm vckit server


And was able to get the VCkit API server up and running:
<img width="1754" alt="Screenshot 2024-11-18 at 11 19 59 AM" src="https://github.com/user-attachments/assets/6a70e436-308c-4f39-8434-c6822ecb3cf5">

Can you please confirm the following:
- The version of node, pnpm and yarn you are using
- The branch you are using
- Have you modified the generated agent.yml file in any way?

**Comment by Givo29** [comment]
Hey @ashleythedeveloper,

Thanks for getting back to me. I was in the process of getting all those versions for you and realised I didn't have yarn installed on my system. Once I installed yarn it's now working fine.

Thanks a lot

**Comment by ashleythedeveloper** [comment]
Thanks for letting us know @Givo29. I've also updated the [bug issue template](https://github.com/uncefact/project-vckit/commit/f9d89a4f4d3e3bdaef8a1bb3e0109c98c9d52ead) to catch these types of problems early in the support process ;)
